version: '3'
services:
  web001:
    build: .
    command: /sbin/init
    privileged: true
    hostname: web001
    ports:
      - '8080:80'
  bastion:
    build: .
    command: /sbin/init
    privileged: true
    hostname: bastion
    ports:
      - '2222:22'
