version: '3'
services:
  web001:
    build:
      context: .
      dockerfile: Dockerfile-agent
    command: /sbin/init
    privileged: true
    hostname: web001.local
    ports:
      - '8080:80'
    links:
      - pmaster:pmaster.local
  pmaster:
    build:
      context: .
      dockerfile: Dockerfile-master
    command: /sbin/init
    privileged: true
    hostname: pmaster.local
