version: '3'
services:
  web:
    image: php:7.3-fpm
    volumes:
      - .:/var/www/app
    depends_on:
      - database
  database:
    image: mysql:5.7
    volumes:
      - ./docker/initdb.d/:/docker-entrypoint-initdb.d/:ro
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
