version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "8000:80"
    depends_on:
      - php
  php:
    build: ./php
    ports:
      - "9000:9000"
  database:
    build: ./database
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: sample:w
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
