version: '3'
services:
  web:
    build: docker/web
    ports:
      - "80:80"
    volumes:
      - .:/var/www/app
    depends_on:
      - database
  database:
    image: mysql:5.7
    volumes:
      - ./docker/database/initdb.d/:/docker-entrypoint-initdb.d/:ro
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    environment:
      TZ: Asia/Tokyo
      MYSQL_DATABASE: sampleapp_development
      MYSQL_USER: sampleapp
      MYSQL_PASSWORD: sampleapp_development
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
